-- Creates a small demo schema in the FREEPDB1 pluggable database.
-- Run as SYS. A dedicated LABTS tablespace lets us lose/restore a single datafile safely.
--
-- NOTE: the table is created only if missing and refreshed with DML (not re-created) on every run.
-- That keeps the table object "old", which matters for Drill 1: Oracle refuses a flashback query on a
-- table created only seconds ago (ORA-01466). run.sh also waits for a brand-new table to age.
alter session set container = FREEPDB1;

-- Use Oracle Managed Files so we can create the tablespace without hard-coding a path.
alter system set db_create_file_dest = '/opt/oracle/oradata' scope = memory;

declare
  e_ts_exists exception;  pragma exception_init(e_ts_exists, -1543); -- tablespace already exists
  e_tab_exists exception; pragma exception_init(e_tab_exists, -955); -- name already used
begin
  begin execute immediate
    'create tablespace labts datafile size 100m autoextend on next 50m';
  exception when e_ts_exists then null; end;

  execute immediate 'alter user labuser quota unlimited on labts';
  execute immediate 'grant execute on dbms_flashback to labuser';

  begin execute immediate
    'create table labuser.orders (
       id        number generated by default as identity primary key,
       customer  varchar2(60),
       amount    number(10,2),
       created   date default sysdate
     ) tablespace labts';
  exception when e_tab_exists then null; end;
end;
/

-- (Re)load 1000 demo rows via DML so the table object keeps its original creation time.
delete from labuser.orders;
insert into labuser.orders (customer, amount)
select 'Customer ' || level, round(dbms_random.value(10, 1000), 2)
from   dual connect by level <= 1000;
commit;

prompt Demo schema ready:
select count(*) as orders_rows from labuser.orders;
