-- AI VECTOR SEARCH DEMO — the same 23ai feature from the post, on Oracle Database Free (no OCI account).
-- Companion to "Your First Oracle Autonomous Database on OCI Always Free". Runs as SYS against FREEPDB1.
set define off
set feedback off
set linesize 120
set pagesize 100
alter session set container = FREEPDB1;

-- idempotent: start clean each run
begin execute immediate 'drop table things purge'; exception when others then null; end;
/

prompt >> Creating a table with a VECTOR column (3 dims -- tiny, just to watch it work)...
create table things (
  id        number generated by default as identity primary key,
  label     varchar2(30),
  embedding vector(3, float32)
);

-- Hand-built embeddings: animals score high on dim 1, vehicles high on dim 3.
insert into things (label, embedding) values ('cat',      to_vector('[0.90, 0.10, 0.00]'));
insert into things (label, embedding) values ('kitten',   to_vector('[0.80, 0.20, 0.00]'));
insert into things (label, embedding) values ('dog',      to_vector('[0.70, 0.30, 0.00]'));
insert into things (label, embedding) values ('airplane', to_vector('[0.00, 0.10, 0.90]'));
insert into things (label, embedding) values ('rocket',   to_vector('[0.00, 0.20, 0.80]'));
commit;

column label    format a12
column distance format 90.9999

prompt
prompt ================================================================
prompt  Nearest neighbors to 'cat'  (COSINE distance, smaller = closer)
prompt ================================================================
select label,
       vector_distance(embedding, to_vector('[0.90, 0.10, 0.00]'), cosine) as distance
from   things
order  by distance
fetch first 5 rows only;

prompt
prompt >> 'kitten' and 'dog' sit closest to 'cat'; 'airplane'/'rocket' are far away.
prompt >> That is semantic search -- query by *similarity*, not exact match. Swap in real
prompt >> model embeddings (hundreds of dims) plus an HNSW/IVF index and it is production AI search.
set feedback on
exit
