-- setup.sql — build the demo schema for the Flashback drills. Run as SYSDBA, AFTER run.sh has enabled
-- ARCHIVELOG + the FRA (a restart). Idempotent (safe to re-run).
--
-- The ACCOUNTS table has ROW MOVEMENT ENABLED — that is a hard requirement for FLASHBACK TABLE ... TO SCN
-- (Oracle physically re-inserts the recovered rows, which changes their rowids). The table is created only
-- if missing and reloaded with DML so the object keeps its original creation time — Oracle refuses a
-- flashback to within ~seconds of a table's creation (ORA-01466), and run.sh waits for it to age.
set echo off feedback off verify off
whenever sqlerror continue
alter session set container = FREEPDB1;

alter system set db_create_file_dest = '/opt/oracle/oradata' scope = both;

declare
  e_user_exists exception; pragma exception_init(e_user_exists, -1920);  -- user already exists
  e_tab_exists  exception; pragma exception_init(e_tab_exists,  -955);   -- name already used
  n number;
begin
  begin execute immediate 'create user labuser identified by "Lab_Passw0rd1" default tablespace users quota unlimited on users';
  exception when e_user_exists then null; end;

  execute immediate 'grant create session, create table, flashback any table to labuser';
  execute immediate 'grant execute on dbms_flashback to labuser';

  begin execute immediate
    'create table labuser.accounts (
       id      number generated by default as identity primary key,
       holder  varchar2(60),
       balance number(12,2),
       updated date default sysdate
     ) enable row movement';
  exception when e_tab_exists then null; end;
end;
/

-- (re)load 1000 rows via DML so the table object keeps its original creation time
delete from labuser.accounts;
insert into labuser.accounts (holder, balance)
  select 'Holder ' || lpad(level, 4, '0'), round(dbms_random.value(100, 10000), 2)
  from   dual connect by level <= 1000;
commit;

prompt Demo schema ready:
select 'ROWS='||count(*) from labuser.accounts;
exit
