-- ============================================================================
-- Wait-events lab — SETUP. Run as SYS (sqlplus -s -L "/ as sysdba").
-- Companion to the post on Oracle wait events. Builds a throwaway schema in
-- FREEPDB1 with four small tables, each sized so the I/O drills genuinely hit
-- disk after a buffer-cache flush, while the whole schema stays a few hundred
-- MB (well under the ~4 GB CI budget).
--
--   t_seq    ~110 MB  indexed  -> 'db file sequential read'  (single-block, index+rowid)
--   t_scat   ~150 MB  heap     -> 'db file scattered read'   (buffered multiblock FTS)
--   t_dpr    ~150 MB  heap     -> 'direct path read'         (serial scan that goes direct)
--   lfs_demo  tiny    heap     -> 'log file sync'            (row-by-row commit loop)
--
-- Reference cache facts on gvenzl/oracle-free (26ai, 8K blocks): DEFAULT buffer
-- cache ~832 MB (~106k blocks), _small_table_threshold ~2036 blocks, so a serial
-- full scan goes "direct path" once a segment is roughly > 5x STT (~80 MB). The
-- scatter drill defeats that with _serial_direct_read=NEVER; the direct drill
-- leans into it with _serial_direct_read=ALWAYS. Sizes below keep both reliable.
--
-- App user is 'labuser' / 'Lab_Passw0rd1' (created by the gvenzl image via
-- APP_USER / APP_USER_PASSWORD), same as the AWR lab. Idempotent: re-runnable.
-- ============================================================================
set echo off feedback off verify off heading off serveroutput on
whenever sqlerror continue

alter session set container = FREEPDB1;

prompt >> Ensuring app user 'labuser' exists with quota...
declare
  n number;
begin
  select count(*) into n from dba_users where username = 'LABUSER';
  if n = 0 then
    -- Normally the image creates labuser from APP_USER; create it if a bare DB is used.
    execute immediate 'create user labuser identified by "Lab_Passw0rd1"';
  end if;
  execute immediate 'grant create session, create table, create procedure to labuser';
  execute immediate 'alter user labuser quota unlimited on users';
end;
/

-- ----------------------------------------------------------------------------
-- Drop any prior copies so re-running setup is clean and sizes are reproducible.
-- ----------------------------------------------------------------------------
prompt >> Dropping any prior lab tables...
begin
  for t in (select table_name from dba_tables
             where owner = 'LABUSER'
               and table_name in ('T_SEQ','T_SCAT','T_DPR','LFS_DEMO'))
  loop
    execute immediate 'drop table labuser.' || t.table_name || ' purge';
  end loop;
end;
/

-- ----------------------------------------------------------------------------
-- t_seq  — indexed table for 'db file sequential read'.
-- 500k rows x ~200-byte pad => ~110 MB heap + a B-tree index on id. An index
-- range scan + TABLE ACCESS BY INDEX ROWID does SINGLE-block reads (P3=1).
-- Rows generated by a 1000 x 500 cross-join (a single 500k CONNECT BY can hit
-- ORA-30009; the cross-join does not).
-- ----------------------------------------------------------------------------
prompt >> Building t_seq (~110 MB, indexed) for the sequential-read drill...
create table labuser.t_seq
as
select rownum as id,
       rpad('x', 200, 'x') as pad
from   (select 1 from dual connect by level <= 1000) a,
       (select 1 from dual connect by level <= 500)  b;

create index labuser.t_seq_id_ix on labuser.t_seq(id);
begin
  dbms_stats.gather_table_stats('LABUSER','T_SEQ',
    cascade => true, estimate_percent => 100);
end;
/

-- ----------------------------------------------------------------------------
-- t_scat — heap table for 'db file scattered read'.
-- ~150 MB. The scatter drill sets _serial_direct_read=NEVER so the FTS stays
-- buffered (multiblock reads into the SGA) regardless of size, which is the
-- whole point of that event. 700k x ~200 bytes via 1000 x 700 cross-join.
-- ----------------------------------------------------------------------------
prompt >> Building t_scat (~150 MB, heap) for the scattered-read drill...
create table labuser.t_scat
as
select rownum as id,
       rpad('y', 200, 'y') as pad
from   (select 1 from dual connect by level <= 1000) a,
       (select 1 from dual connect by level <= 700)  b;

begin
  dbms_stats.gather_table_stats('LABUSER','T_SCAT', estimate_percent => 100);
end;
/

-- ----------------------------------------------------------------------------
-- t_dpr  — heap table for 'direct path read'.
-- ~150 MB, comfortably above ~5x _small_table_threshold (~80 MB) so a serial
-- full scan goes direct even under the default AUTO heuristic. The direct drill
-- also pins it with _serial_direct_read=ALWAYS for determinism.
-- ----------------------------------------------------------------------------
prompt >> Building t_dpr (~150 MB, heap) for the direct-path drill...
create table labuser.t_dpr
as
select rownum as id,
       rpad('z', 200, 'z') as pad
from   (select 1 from dual connect by level <= 1000) a,
       (select 1 from dual connect by level <= 700)  b;

begin
  dbms_stats.gather_table_stats('LABUSER','T_DPR', estimate_percent => 100);
end;
/

-- ----------------------------------------------------------------------------
-- lfs_demo — tiny heap table for 'log file sync'. The commit loop populates it.
-- ----------------------------------------------------------------------------
prompt >> Building lfs_demo (tiny) for the commit drill...
create table labuser.lfs_demo (id number, pad varchar2(100));

-- ----------------------------------------------------------------------------
-- Report what we built.
-- ----------------------------------------------------------------------------
set heading on
column segment_name format a12
column size_mb      format 9990.0
prompt
prompt Lab schema ready (sizes are on-disk segment MB):
select segment_name,
       round(bytes/1024/1024, 1) as size_mb
from   dba_segments
where  owner = 'LABUSER'
  and  segment_name in ('T_SEQ','T_SEQ_ID_IX','T_SCAT','T_DPR','LFS_DEMO')
order  by bytes desc;

column total_mb format 99990.0
select round(sum(bytes)/1024/1024, 1) as total_schema_mb
from   dba_segments
where  owner = 'LABUSER';
exit

