-- Minimal demo schema for the AWR drill: a small table the workload can hammer.
-- Run as SYS. Created in FREEPDB1, owned by labuser.
alter session set container = FREEPDB1;

declare
  e_tab_exists exception; pragma exception_init(e_tab_exists, -955); -- name already used
begin
  begin execute immediate
    'create table labuser.orders (
       id        number generated by default as identity primary key,
       customer  varchar2(60),
       amount    number(10,2),
       created   date default sysdate
     )';
  exception when e_tab_exists then null; end;
end;
/

delete from labuser.orders;
insert into labuser.orders (customer, amount)
select 'Customer ' || level, round(dbms_random.value(10, 1000), 2)
from   dual connect by level <= 1000;
commit;

prompt Demo schema ready:
select count(*) as orders_rows from labuser.orders;
