-- Demo schema for the AWR lab. Run as SYS.
--   orders  — a small table
--   bigtab  — a ~470 MB table (bigger work set) for the I/O drill
-- Also raises AWR's SQL capture so the workload statement reliably appears in reports.

-- At the CDB root: capture more SQL per snapshot so the drill's statement shows up in the report.
begin
  dbms_workload_repository.modify_snapshot_settings(topnsql => 100);
end;
/

alter session set container = FREEPDB1;

declare
  e_tab_exists exception; pragma exception_init(e_tab_exists, -955);
begin
  begin execute immediate
    'create table labuser.orders (
       id number generated by default as identity primary key,
       customer varchar2(60), amount number(10,2), created date default sysdate)';
  exception when e_tab_exists then null; end;
end;
/
delete from labuser.orders;
insert into labuser.orders (customer, amount)
select 'Customer ' || level, round(dbms_random.value(10, 1000), 2)
from   dual connect by level <= 1000;
commit;

-- bigger-than-the-buffer-cache table for the I/O drill, so full scans must hit disk every time
-- (4M rows x ~315 bytes ~= 1.2GB, vs a ~960MB cache). Rebuilt each setup for reproducibility.
-- Rows come from a cross-join of two small generators — a single 4M-row CONNECT BY runs out of
-- memory (ORA-30009), but 2000 x 2000 does not.
begin execute immediate 'drop table labuser.bigtab purge'; exception when others then null; end;
/
create table labuser.bigtab as
select rownum as id, rpad('x', 300, 'x') as filler, mod(rownum, 1000) as grp
from   (select 1 from dual connect by level <= 2000) a,
       (select 1 from dual connect by level <= 2000) b;

prompt Demo schema ready:
select (select count(*) from labuser.orders) as orders_rows,
       round((select bytes/1024/1024 from dba_segments
              where owner='LABUSER' and segment_name='BIGTAB')) as bigtab_mb
from dual;
